name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
                    # Options
          user: OnscreenProton
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: UTC
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_visibility: all
          plugin_anilist: yes
          plugin_anilist_limit.characters: 22
          plugin_anilist_limit: 5
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: watching
          plugin_anilist_shuffle: yes
          plugin_anilist_user: .user.login
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_ignored: glsl
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_notable: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_traffic: yes
